version: '3.1'

services:
    www:
      build: .
      ports: 
          - "8000:80"
      volumes:
          - ./www:/var/www/html/
      networks:
          - default
    ftpd_server:
        image: stilliard/pure-ftpd:hardened
        # container_name: pure-ftpd
        ports:
            - "21:21"
            - "30000-30009:30000-30009"
        volumes:
            - ./data:/home/ftpuser/
            - ./passwd:/etc/pure/pure-ftpd/passwd
        environment:
            # PUBLICHOST: "10.30.140.105"
            FTP_USER_NAME: "ftpuser"
            FTP_USER_PASS: 1234
            FTP_USER_HOME: /home/ftpuser
        #restart: always
